# Generated by Django 4.0.1 on 2022-01-09 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alumnos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('grado', models.IntegerField(null=True)),
                ('seccion', models.IntegerField(null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('padre', models.CharField(max_length=100)),
                ('madre', models.CharField(max_length=100)),
            ],
        ),
    ]
