# Generated by Django 4.0.1 on 2022-01-09 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librerua', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnos',
            name='ingreso',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='alumnos',
            name='nacimiento',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
