# Generated by Django 4.0.1 on 2022-01-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librerua', '0002_alumnos_ingreso_alumnos_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='grado',
            field=models.IntegerField(null=True, verbose_name='Grado'),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='ingreso',
            field=models.PositiveIntegerField(null=True, verbose_name='Año de ingreso'),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='madre',
            field=models.CharField(max_length=100, verbose_name='Nombre de la Madre'),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='nacimiento',
            field=models.PositiveIntegerField(null=True, verbose_name='Año de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre del Alumno'),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='padre',
            field=models.CharField(max_length=100, verbose_name='Nombre del Padre'),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='seccion',
            field=models.IntegerField(null=True, verbose_name='Sección'),
        ),
    ]
